# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('savas', 'SAVAS'), ('strateji', 'STRATEJI'), ('spor', 'SPOR'), ('bulmaca', 'BULMACA'), ('diger', 'DIGER')], default='bulmaca', max_length=6),
        ),
    ]
