# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20171218_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upload_link',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=b'defaultt', upload_to=b'files/'),
        ),
    ]
