# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_auto_20171218_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creator',
        ),
    ]
