# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_remove_post_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(default=b'default', upload_to=b'files/'),
        ),
    ]
