# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160801_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('savas', 'SAVAS'), ('strateji', 'STRATEJI'), ('spor', 'SPOR'), ('bulmaca', 'BULMACA'), ('diger', 'DIGER')], default='bulmaca', max_length=6),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='empty', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
